In [2]:
import numpy as np

## Tipos de datos
arr.dtype, arr.astype(np.float64,bool_, string_), 

In [5]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
list4 = [0.5,1,1.5,2]

In [10]:
arr1 = np.array(list1)
arr2 = np.array(list2)
arr3 = np.array(list3)
arr4 = np.array(list4)
matriz = np.array([list1, list2, list3])

In [17]:
arr1.dtype, arr4.dtype, matriz.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [22]:
arr1 = arr1.astype(np.float64)
arr2 = arr2.astype(np.float64)

## Dimensiones
![Captura.PNG](https://static.platzi.com/media/user_upload/Captura-421aa63c-d409-4d5f-9029-c2242d69b86d.jpg)

### Comandos
scalar.ndim

In [31]:
scalar = np.array(50)
print(scalar)
scalar.ndim

50


0

In [33]:
vecto = np.array([1,2,3,4])
print(vector)
vector.ndim

[1 2 3 4]


1

In [35]:
matrix = np.array([[1,2,3,4],[5,6,7,8]])
print(matrix)
matrix.ndim

[[1 2 3 4]
 [5 6 7 8]]


2

In [37]:
tensor = np.array([[[1,2,3,4],[5,6,7,8]],[[9,12,13,14],[15,16,17,18]]])
print(tensor)
tensor.ndim

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 12 13 14]
  [15 16 17 18]]]


3

In [39]:
tensor = np.array([[[[1,2,3,4],[5,6,7,8]],[[9,12,13,14],[15,16,17,18]]],[[[1,2,3,4],[5,6,7,8]],[[9,12,13,14],[15,16,17,18]]]])
print(tensor)
tensor.ndim

[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 12 13 14]
   [15 16 17 18]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 12 13 14]
   [15 16 17 18]]]]


4