In [1]:
import numpy as np

## Tipos de datos
arr.dtype, arr.astype(np.float64,bool_, string_), 

In [2]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
list4 = [0.5,1,1.5,2]

In [3]:
arr1 = np.array(list1)
arr2 = np.array(list2)
arr3 = np.array(list3)
arr4 = np.array(list4)
matriz = np.array([list1, list2, list3])

In [4]:
arr1.dtype, arr4.dtype, matriz.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [5]:
arr1 = arr1.astype(np.float64)
arr2 = arr2.astype(np.float64)

## Dimensiones
![Captura.PNG](https://static.platzi.com/media/user_upload/Captura-421aa63c-d409-4d5f-9029-c2242d69b86d.jpg)

### Comandos
scalar.ndim

In [6]:
scalar = np.array(50)
print(scalar)
scalar.ndim

50


0

In [8]:
vector = np.array([1,2,3,4])
print(vector)
vector.ndim

[1 2 3 4]


1

In [9]:
matrix = np.array([[1,2,3,4],[5,6,7,8]])
print(matrix)
matrix.ndim

[[1 2 3 4]
 [5 6 7 8]]


2

In [10]:
tensor = np.array([[[1,2,3,4],[5,6,7,8]],[[9,12,13,14],[15,16,17,18]]])
print(tensor)
tensor.ndim

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 12 13 14]
  [15 16 17 18]]]


3

In [11]:
tensor = np.array([[[[1,2,3,4],[5,6,7,8]],[[9,12,13,14],[15,16,17,18]]],[[[1,2,3,4],[5,6,7,8]],[[9,12,13,14],[15,16,17,18]]]])
print(tensor)
tensor.ndim

[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 12 13 14]
   [15 16 17 18]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 12 13 14]
   [15 16 17 18]]]]


4

## Agregar o eliminar dimensiones

In [12]:
vector = np.array([1,2,3,4],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3 4]]]]]]]]]]


10

In [13]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand, expand.ndim)

[[1 2 3]] 2


### Eliminar dims

In [14]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]] 10
[1 2 3 4] 1


## Creando arrays

#### np.arange

In [19]:
list1 = np.arange(0,10)
list2 = np.arange(0,20,2)
print(list1,list2)

[0 1 2 3 4 5 6 7 8 9] [ 0  2  4  6  8 10 12 14 16 18]


#### np.zeros

In [20]:
np.zeros(4)

array([0., 0., 0., 0.])

In [23]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### Crea una array con la cantidad de numeros que le pidas, en el rango solicitado

In [25]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

#### Crea una matriz con diagonal 1

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Crear un array con numeros random

In [27]:
np.random.rand(4)

array([0.04086892, 0.24497166, 0.48348637, 0.18764757])

#### Crear un array con numeros enteros random

In [28]:
np.random.randint(1,75,(10,10))

array([[ 1, 29, 31, 11, 29, 44, 15, 66,  5, 32],
       [ 3,  4, 31, 69, 51, 35,  8, 37, 41, 50],
       [36, 68, 22, 24, 16, 13, 42,  9, 20, 50],
       [51, 10, 28, 63,  3, 45,  6, 36, 52, 71],
       [61, 25, 69, 31, 10, 26, 61, 44, 60, 58],
       [28, 64, 21,  5, 66,  3,  9, 41, 71, 20],
       [72, 48, 39, 51,  2, 68, 44, 25, 45, 52],
       [ 3, 64,  6, 39, 41, 34, 67, 73, 42, 50],
       [71, 21, 20,  4, 17, 28, 38, 48, 52, 30],
       [ 4, 13, 38, 62, 53, 71, 49, 63,  9, 30]])

## Shape y Reshape

In [31]:
arr_1 = np.random.randint(1,10,(3,2))

In [32]:
arr_1.shape

(3, 2)

In [33]:
arr_1.reshape(1,6)

array([[9, 3, 8, 6, 9, 7]])

In [34]:
arr_1.reshape(2,3)

array([[9, 3, 8],
       [6, 9, 7]])

#### Hacer Reshape como lo haria el lenguaje C

In [35]:
np.reshape(arr_1,(2,3),'C')

array([[9, 3, 8],
       [6, 9, 7]])

#### Hacer Reshape como lo haria el lenguaje Fortran

In [36]:
np.reshape(arr_1,(2,3),'F')

array([[9, 9, 6],
       [8, 3, 7]])

#### Hacer Reshape como lo haria de la forma mas optima

In [37]:
np.reshape(arr_1,(2,3),'A')

array([[9, 3, 8],
       [6, 9, 7]])

### Reto de la clase

In [44]:
reto_array = np.random.randint(1,50,(8,4))
reto_array

array([[44, 39, 23, 18],
       [23,  5, 21, 35],
       [12, 44, 44, 21],
       [20, 49, 27, 39],
       [12, 26, 27, 36],
       [37, 48,  6,  2],
       [44,  8,  5, 14],
       [32, 23, 25, 10]])

In [41]:
np.reshape(reto_array, (2,16))

array([[44, 11, 36, 45,  3, 42, 39, 28, 12, 17,  6, 44, 41, 32, 33, 12],
       [ 9, 10, 42,  2, 48,  6, 42,  6, 24, 20, 41, 45, 15, 32, 19, 29]])

In [45]:
np.reshape(reto_array, (3,16))

ValueError: cannot reshape array of size 32 into shape (3,16)

## Funciones principales Numpy

In [93]:
arr = np.random.randint(1,30,10)


In [50]:
matriz = arr.reshape(2,5)
matriz

array([[18, 12,  9, 27, 28],
       [ 9, 18, 14,  9, 29]])

#### .max() Traer el numero maximo

In [51]:
arr.max()

29

In [52]:
matriz.max()

29

In [54]:
matriz.max(0)

array([18, 18, 14, 27, 29])

#### argmax() indica el indice del valor mas alto

In [55]:
matriz.argmax()

9

#### .min() Traer el numero maximo

In [56]:
arr.min()

9

In [57]:
matriz.min()

9

In [58]:
matriz.min(0)

array([ 9, 12,  9,  9, 28])

In [60]:
matriz.argmin(1)

array([2, 0])

#### .ptp() saber la diferencia de numeros que existe del numero mas bajo al mas alto (de pico a pico)

In [63]:
arr

array([18, 12,  9, 27, 28,  9, 18, 14,  9, 29])

In [61]:
arr.ptp()

20

In [64]:
matriz

array([[18, 12,  9, 27, 28],
       [ 9, 18, 14,  9, 29]])

In [65]:
matriz.ptp(0)

array([ 9,  6,  5, 18,  1])

#### np.sort() orderna los valores de la array

In [69]:
arr.sort()
arr

array([ 9,  9,  9, 12, 14, 18, 18, 27, 28, 29])

#### np.percentile(arr, 50) poder saber el valor que se encuentra en la posicion indicada en porcentaje

In [68]:
np.percentile(arr,50)

16.0

#### np.median(arr) me da la mediana del array

In [70]:
np.median(arr)

16.0

In [72]:
np.median(matriz,1)

array([ 9., 27.])

#### np.std() nos da la desviacion estandar.

In [73]:
np.std(arr)

7.694803441284254

#### np.var() nos da la varianza --> que es igual a la desviacion estandar ** 2

In [74]:
np.var(arr)

59.21

#### np.mean() nos entrega la media de nuestra array

In [75]:
np.mean(arr)

17.3

#### np.concatenate((a,b) axis=0) me une las dos arrays

In [76]:
a = np.array([[1,2],[3,4]])
b = np.array([4,6]) 

In [79]:
b = np.expand_dims(b,axis=0)
b.ndim

2

In [83]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [4, 6]])

#### si se le anade la T nos da la transpuesta

In [86]:
b.T

array([[4],
       [6]])

In [85]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 4],
       [3, 4, 6]])

## Copy

#### .copy() creado para poder copiar la array en otra variable y no se modifique la original

In [105]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
arr_cortado = arr[0:6].copy()
arr_cortado[:] = 0
arr_cortado

array([0, 0, 0, 0, 0, 0])

In [107]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])