In [2]:
import numpy as np

## Tipos de datos
arr.dtype, arr.astype(np.float64,bool_, string_), 

In [3]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
list4 = [0.5,1,1.5,2]

In [4]:
arr1 = np.array(list1)
arr2 = np.array(list2)
arr3 = np.array(list3)
arr4 = np.array(list4)
matriz = np.array([list1, list2, list3])

In [5]:
arr1.dtype, arr4.dtype, matriz.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [6]:
arr1 = arr1.astype(np.float64)
arr2 = arr2.astype(np.float64)

## Dimensiones
![Captura.PNG](https://static.platzi.com/media/user_upload/Captura-421aa63c-d409-4d5f-9029-c2242d69b86d.jpg)

### Comandos
scalar.ndim

In [7]:
scalar = np.array(50)
print(scalar)
scalar.ndim

50


0

In [8]:
vector = np.array([1,2,3,4])
print(vector)
vector.ndim

[1 2 3 4]


1

In [9]:
matrix = np.array([[1,2,3,4],[5,6,7,8]])
print(matrix)
matrix.ndim

[[1 2 3 4]
 [5 6 7 8]]


2

In [10]:
tensor = np.array([[[1,2,3,4],[5,6,7,8]],[[9,12,13,14],[15,16,17,18]]])
print(tensor)
tensor.ndim

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 12 13 14]
  [15 16 17 18]]]


3

In [11]:
tensor = np.array([[[[1,2,3,4],[5,6,7,8]],[[9,12,13,14],[15,16,17,18]]],[[[1,2,3,4],[5,6,7,8]],[[9,12,13,14],[15,16,17,18]]]])
print(tensor)
tensor.ndim

[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 12 13 14]
   [15 16 17 18]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 12 13 14]
   [15 16 17 18]]]]


4

## Agregar o eliminar dimensiones

In [12]:
vector = np.array([1,2,3,4],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3 4]]]]]]]]]]


10

In [13]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand, expand.ndim)

[[1 2 3]] 2


### Eliminar dims

In [14]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]] 10
[1 2 3 4] 1


## Creando arrays

#### np.arange

In [15]:
list1 = np.arange(0,10)
list2 = np.arange(0,20,2)
print(list1,list2)

[0 1 2 3 4 5 6 7 8 9] [ 0  2  4  6  8 10 12 14 16 18]


#### np.zeros

In [16]:
np.zeros(4)

array([0., 0., 0., 0.])

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### Crea una array con la cantidad de numeros que le pidas, en el rango solicitado

In [19]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

#### Crea una matriz con diagonal 1

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Crear un array con numeros random

In [21]:
np.random.rand(4)

array([0.65943128, 0.79166008, 0.46487579, 0.9866675 ])

#### Crear un array con numeros enteros random

In [22]:
np.random.randint(1,75,(10,10))

array([[51, 21, 10, 39, 18,  9, 20, 32,  7, 20],
       [ 7, 12, 33, 20, 22, 64, 11, 74, 31, 34],
       [38, 30, 68, 25, 40, 52, 61,  1, 11, 42],
       [28, 74, 69, 70, 34, 27, 23, 39, 15, 42],
       [49,  1, 51, 22, 56, 10, 62, 72, 45, 34],
       [70, 43, 47, 61, 71, 70, 17, 10, 32, 59],
       [34, 39, 54, 54, 74, 58,  8, 44, 39, 13],
       [56, 20, 44, 73, 73, 65, 65, 35, 28,  1],
       [51, 33, 10, 48, 46, 12, 39, 41, 19, 37],
       [48,  5, 64,  4, 59, 66, 50, 41, 12, 25]])

## Shape y Reshape

In [23]:
arr_1 = np.random.randint(1,10,(3,2))

In [24]:
arr_1.shape

(3, 2)

In [25]:
arr_1.reshape(1,6)

array([[7, 5, 6, 1, 1, 5]])

In [26]:
arr_1.reshape(2,3)

array([[7, 5, 6],
       [1, 1, 5]])

#### Hacer Reshape como lo haria el lenguaje C

In [27]:
np.reshape(arr_1,(2,3),'C')

array([[7, 5, 6],
       [1, 1, 5]])

#### Hacer Reshape como lo haria el lenguaje Fortran

In [28]:
np.reshape(arr_1,(2,3),'F')

array([[7, 1, 1],
       [6, 5, 5]])

#### Hacer Reshape como lo haria de la forma mas optima

In [29]:
np.reshape(arr_1,(2,3),'A')

array([[7, 5, 6],
       [1, 1, 5]])

### Reto de la clase

In [30]:
reto_array = np.random.randint(1,50,(8,4))
reto_array

array([[39, 23, 37, 17],
       [23, 31, 32, 49],
       [42, 14, 29, 18],
       [ 2, 19, 45, 20],
       [16,  3,  9, 21],
       [19, 38, 46, 31],
       [19, 33, 23, 44],
       [13, 11, 46, 32]])

In [31]:
np.reshape(reto_array, (2,16))

array([[39, 23, 37, 17, 23, 31, 32, 49, 42, 14, 29, 18,  2, 19, 45, 20],
       [16,  3,  9, 21, 19, 38, 46, 31, 19, 33, 23, 44, 13, 11, 46, 32]])

In [32]:
np.reshape(reto_array, (3,16))

ValueError: cannot reshape array of size 32 into shape (3,16)

## Funciones principales Numpy

In [ ]:
arr = np.random.randint(1,30,10)


In [ ]:
matriz = arr.reshape(2,5)
matriz

array([[18, 12,  9, 27, 28],
       [ 9, 18, 14,  9, 29]])

#### .max() Traer el numero maximo

In [ ]:
arr.max()

29

In [ ]:
matriz.max()

29

In [ ]:
matriz.max(0)

array([18, 18, 14, 27, 29])

#### argmax() indica el indice del valor mas alto

In [ ]:
matriz.argmax()

9

#### .min() Traer el numero maximo

In [ ]:
arr.min()

9

In [ ]:
matriz.min()

9

In [ ]:
matriz.min(0)

array([ 9, 12,  9,  9, 28])

In [ ]:
matriz.argmin(1)

array([2, 0])

#### .ptp() saber la diferencia de numeros que existe del numero mas bajo al mas alto (de pico a pico)

In [ ]:
arr

array([18, 12,  9, 27, 28,  9, 18, 14,  9, 29])

In [ ]:
arr.ptp()

20

In [ ]:
matriz

array([[18, 12,  9, 27, 28],
       [ 9, 18, 14,  9, 29]])

In [ ]:
matriz.ptp(0)

array([ 9,  6,  5, 18,  1])

#### np.sort() orderna los valores de la array

In [ ]:
arr.sort()
arr

array([ 9,  9,  9, 12, 14, 18, 18, 27, 28, 29])

#### np.percentile(arr, 50) poder saber el valor que se encuentra en la posicion indicada en porcentaje

In [ ]:
np.percentile(arr,50)

16.0

#### np.median(arr) me da la mediana del array

In [ ]:
np.median(arr)

16.0

In [ ]:
np.median(matriz,1)

array([ 9., 27.])

#### np.std() nos da la desviacion estandar.

In [ ]:
np.std(arr)

7.694803441284254

#### np.var() nos da la varianza --> que es igual a la desviacion estandar ** 2

In [ ]:
np.var(arr)

59.21

#### np.mean() nos entrega la media de nuestra array

In [ ]:
np.mean(arr)

17.3

#### np.concatenate((a,b) axis=0) me une las dos arrays

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([4,6]) 

In [ ]:
b = np.expand_dims(b,axis=0)
b.ndim

2

In [ ]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [4, 6]])

#### si se le anade la T nos da la transpuesta

In [ ]:
b.T

array([[4],
       [6]])

In [ ]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 4],
       [3, 4, 6]])

## Copy

#### .copy() creado para poder copiar la array en otra variable y no se modifique la original

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_cortado = arr[0:6].copy()
arr_cortado[:] = 0
arr_cortado

array([0, 0, 0, 0, 0, 0])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Condiciones

#### Condiciona a las arrays mostrando solo lo que queremos arr[arr>condicion]

In [38]:
n_array = np.linspace(0,10,10, dtype='int32' )
n_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10])

In [41]:
n_array[(n_array>5) & (n_array<9)]

array([6, 7, 8])

## Operaciones

In [52]:
array_o= np.random.randint(20,45,15)
array_o

array([43, 22, 42, 29, 20, 35, 44, 39, 28, 43, 30, 26, 34, 27, 29])

In [53]:
arr_copy = array_o.copy()
arr_copy

array([43, 22, 42, 29, 20, 35, 44, 39, 28, 43, 30, 26, 34, 27, 29])

#### Operaciones

In [55]:
array_o*2

array([86, 44, 84, 58, 40, 70, 88, 78, 56, 86, 60, 52, 68, 54, 58])

In [56]:
array_o + 5

array([48, 27, 47, 34, 25, 40, 49, 44, 33, 48, 35, 31, 39, 32, 34])

In [58]:
array_o / 3

array([14.33333333,  7.33333333, 14.        ,  9.66666667,  6.66666667,
       11.66666667, 14.66666667, 13.        ,  9.33333333, 14.33333333,
       10.        ,  8.66666667, 11.33333333,  9.        ,  9.66666667])

In [59]:
array_o ** 2

array([1849,  484, 1764,  841,  400, 1225, 1936, 1521,  784, 1849,  900,
        676, 1156,  729,  841])

In [60]:
array_o + arr_copy

array([86, 44, 84, 58, 40, 70, 88, 78, 56, 86, 60, 52, 68, 54, 58])

In [61]:
array_o * arr_copy

array([1849,  484, 1764,  841,  400, 1225, 1936, 1521,  784, 1849,  900,
        676, 1156,  729,  841])

In [64]:
matriz_ar = array_o.reshape(5,3)
matriz_2 = matriz_ar.copy()

In [65]:
matriz_ar

array([[43, 22, 42],
       [29, 20, 35],
       [44, 39, 28],
       [43, 30, 26],
       [34, 27, 29]])

### Producto punto np.matmul o matriz1 @ matriz2

In [69]:
np.matmul(matriz_ar,matriz_2.T)

array([[4097, 3157, 3926, 3601, 3274],
       [3157, 2466, 3036, 2757, 2541],
       [3926, 3036, 4241, 3790, 3361],
       [3601, 2757, 3790, 3425, 3026],
       [3274, 2541, 3361, 3026, 2726]])

In [70]:
matriz_ar @ matriz_2.T

array([[4097, 3157, 3926, 3601, 3274],
       [3157, 2466, 3036, 2757, 2541],
       [3926, 3036, 4241, 3790, 3361],
       [3601, 2757, 3790, 3425, 3026],
       [3274, 2541, 3361, 3026, 2726]])